### ISSUE TITLE
how to implement redirect after payment？

### ISSUE THREAD

**Issue by socoolcompany** [paylike/sdk#12]
Just a basic question about the SDK:
Can you help me with the js code in the SDK to add a redirect url?
for example, when the customer finishes their payment in the popup window then he will be redirected to www.google.com
How to implement it with modifying the js code? :)

**Comment by tjconcept** [comment]
Hi @socoolcompany 

This is a general JavaScript question which is not really related to Paylike. You should instead ask in such a forum.

One way to redirect a browser is by reassigning `location.href`.
