### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by javlund** [paylike/sdk#14]
Hi guys,

2 questions:

1. Are you considering creating a version of the SDK that is published to npm and doesn't pollute the global scope with the `Paylike` variable?
2. Irrelevant if the answer to the first question is "yes", but in the examples I see different files included (`2.js`, `3.js`, `4.js`), and I can see that `5.js` and `6.js` also exist. What's the difference between these files? Which should be used when using the SDK?

**Comment by tjconcept** [comment]
Hi @javlund 

1) Yes, that's on our roadmap, and to leak a little insider information, we're going to soon (couple months) publish new versions of both the popup and lower-level functions. "Versions" in plural because the plan is to separate the popup from the rest.

2) I'm sorry about the confusion created, but we've used those filenames when slowly rolling out updated versions, however, the API is the same, and as we've finished testing, we've merged them together. So, the answer is: it doesn't matter. If you use `6.js`, you'll get a bit newer code (I'd suggest if you're testing now anyway), but they will all merge again in a couple weeks.

**Comment by javlund** [comment]
Awesome @tjconcept - thanks for a swift answer on a Friday night.

I'll keep an eye out for the new versions!

**Comment by tjconcept** [comment]
Just a bit of a status on this one:

We've released https://www.npmjs.com/package/@paylike/client (example use: https://github.com/paylike/api-reference/blob/master/payments/example-client.js) for low-level implementations. It doesn't need to do any HTML-related stuff and therefore is fully encapsulated.

On the SDK (which there's also a new version), we are discussing internally how to do it. We have two main issues:
1. The popup needs to preload CSS to avoid blinking once it is opened. To do so, we attach stuff do the DOM which is obviously global. We keep a global value to ensure we only do that once.
2. The popup needs to attach itself to the DOM and also add a listener on the window object, therefore, regardless of what we do, it will always have a "smell of globalness". Best idea at the moment is allowing injection of DOM objects, but it seems the use case is very slim for ever changing those.

To achieve actual encapsulation, you most likely need to built stuff yourself specific to whatever framework/religion you use, such as a React-specific model component. We are considering additional helpers we could build to make such easier.

**Comment by javlund** [comment]
Hi @tjconcept , thanks for that update - your timing is spot on as we're discussing re-implementing Paylike support these days. I will look into the npm package and see what I can achieve with it.

For what it's worth, we're using React, so an official helper component for that would be great. But maybe I can build a wrapper myself around it.

**Comment by javlund** [comment]
Hi @tjconcept - sorry to revive a closed issue.

I've been tinkering with this and can get it to work in test, but I worry about 3D-secure support. Is it possible for you to either:
1. Give me a brief code example as to how I would go about using the npm package with 3DS support, or
2. Give me an idea as to how I could use the popup as cleanly and isolated as possible in a React website?

Thanks for helping out.

**Comment by tjconcept** [comment]
No problem.

This should be that example: https://github.com/paylike/api-reference/blob/main/payments/example-client.js. After implementing that, you support all our transaction capabilities, such as 3-D Secure.
What do feel like your are missing?

For React I suppose you could replace the `ce` function with a reactive style `render` method and some state. I'm not sure exactly what the React-correct way of posting to an iframe is though, it is kind-of against the idea, but unfortunately the way 3-D Secure is defined.
Basically, you should be able to re-build the popup in React if you wanted to.

If you are using the popup, what we've done ourselves for pos.paylike.io is something along the lines of:

1. Include `<script src="https://sdk.paylike.io/10.js"></script>` in the HTML
2. Initiate `paylike` in the top app-element (`this.paylike = Paylike({key: this.props.publicKey})`)
3. Expose a `pay` function from the top element to children needing it (through "props")
4. Call `this.paylike.pay` in the exposes `pay` function

I'm sure there's a more react-ish way fo doing (1), something like registering scripts such that no dupes are added.

**Comment by javlund** [comment]
Hi @tjconcept - I've tried implementing this as per the non-popup example provided, in a marginally more Reactish way.

It seems to work in test, but in production I'm getting this after going through a few challenges (the final one at `/payments/challenges/tds-legacy-enrolled`):
`{"code":"TDSECURE_REQUIRED","message":"3-D Secure is required but is not supported by the payment method at the moment."}`

The API docs are a bit unclear as to exactly why this occurs. Is this due to an error in our account setup (these accounts are a bit old) or is it because the implementation is wrong?

Also - the docs state that it is required to dynamically create and destroy the iframes each time, which I'm faithfully doing, but is this really necessary? DOM manipulation doesn't go very well with React so I try to minimize it.

**Comment by tjconcept** [comment]
> It seems to work in test, but in production I'm getting this after going through a few challenges (the final one at `/payments/challenges/tds-legacy-enrolled`):
> `{"code":"TDSECURE_REQUIRED","message":"3-D Secure is required but is not supported by the payment method at the moment."}`
> 
> The API docs are a bit unclear as to exactly why this occurs. Is this due to an error in our account setup (these accounts are a bit old) or is it because the implementation is wrong?

This error code should only occur if 3-D Secure is not supported by the payment card or it failed for some reason.

If you can provide me the `X-Client` header from an example exchange, I can look it up more closely. Alternatively, if you have a test site available, I'll give that a try.

> Also - the docs state that it is required to dynamically create and destroy the iframes each time, which I'm faithfully doing, but is this really necessary? DOM manipulation doesn't go very well with React so I try to minimize it.

It wasn't meant to be interpreted that strictly. I'll see if I can moderate it without complicating it further. As far as I can tell, you should be fine simply posting to the same iframe.

**Comment by javlund** [comment]
Wow, that was a fast response late at night. Thanks.

I was just using a bogus card ID, like 121212121212121 etc., but I would actually have thought that it would be caught by another error. I'll try with a real one next. For reference, the `X-Request-ID` was `462439b6f78d582e1d7f5b48389beb73` (`X-Client` of request was `js-c-1`).

**Comment by javlund** [comment]
I managed to get the NemID box up now with a proper CC number (even though the expiry + CVC was still bogus). Still a way to go, but at least there's progress now. Again thanks for the super swift reply.

**Comment by tjconcept** [comment]
> Thanks.

You're welcome.

> I was just using a bogus card ID, like 121212121212121 etc., but I would actually have thought that it would be caught by another error. I'll try with a real one next.

Ah, I see. You should definitely use the test mode, then you can trigger different scenarios with challenges: https://github.com/paylike/api-reference/blob/main/payments/index.md#test.

> (even though the expiry + CVC was still bogus)

Ah, yes, Nets is *that* stupid. It will fail later.

Let me know where you tripped on the way, you're definitely not the last, so if I can provide some more hints in the docs..
