### ISSUE TITLE
Pay as you like button integration with Wordpress/Divi

### ISSUE THREAD

**Issue by sicambria** [paylike/sdk#16]
Hi,
I'd like to integrate Paylike as a "Pay as you like" option to Wordpress/Divi.

I've added the button and script part to Divi's "HTML code" module from here:
https://github.com/paylike/sdk/blob/main/examples/popup-minimal.html

However, nothing happens when I click on the button (the grey one) here:
https://inczegaspar.hu/pay/

Could you please help how to fix this?

**Comment by tjconcept** [comment]
Hi @sicambria 

It looks like a problem with your integration. There's a syntax error in the JavaScript supposed to open the payment popup.

Unfortunately, we can not provide general programming help, so I would suggest you reach out to someone with JavaScript experience on a forum, freelance website, or likewise.
