### ISSUE TITLE
not working on IE8 and Safari windows

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [paylike/sdk#6]
I know these browsers are pretty old now, but still hundreds of thousands of computers are still using it, though it represents a low percentage worldwide.
on IE8, Paylike object is null,
on Safari windows,  TypeError: 'undefined' is not an object (evaluating 'paylike.popup')
Also is it possible to get a human readable source of your js script?
actually it generates a lot of non fatal js error and slow down the browser.
using strict on the error console will show all the errors.

**Comment by tjconcept** [comment]
Hi @madovsky 

Thank you for posting this issue.
I am sorry about the late reply, this issue had simply slipped from my attention.

I am afraid IE 8, 9 and Safari on Windows (only a very old version available for that platform right?) are too old to support in a secure manner.
Without special configuration they cannot meet the requirements in the PCI DSS (Visa, Mastercard, etc. mandatory security standard), for instance on the TLS/SSL section, and it is my belief that any provider supporting these browsers are both in violation and doing a disservice to their customers.

> Also is it possible to get a human readable source of your js script?

I am afraid not at the moment, but it is a long term goal to open source it.

> actually it generates a lot of non fatal js error and slow down the browser.

I've had another look and I only see 4-5 warnings all related code style preferences (2 stems from Lodash modules).
Could you add details as to how to measure and reproduce the performance hit you are seeing?

**Comment by tjconcept** [comment]
I'm gonna close this as it's not currently actionable. Feel free to reopen if you have more information to add.
